{
 "title": "Sensors",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Tempreture",
   "type": "graph",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT  value FROM \"mqtt_consumer\"  WHERE  topic = 'esp/temp'  and  \"value\" != -127 and \"value\" >  10 and \"value\" < 80 and $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Moisture",
   "type": "graph",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT  MEAN(\"value\") FROM \"mqtt_consumer\"  WHERE  topic = 'esp/moisture'  and   $timeFilter  GROUP BY time(30m)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PH",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT MEAN(\"value\") FROM \"mqtt_consumer\"  WHERE  topic = 'esp/ph'  and $timeFilter GROUP BY time(2h)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max/Min temp of the day",
   "type": "graph",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MIN(\"value\") FROM \"mqtt_consumer\"  WHERE  topic = 'esp/temp'  and value < 70 and value != -127 and $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MAX(\"value\") FROM \"mqtt_consumer\"  WHERE  topic = 'esp/temp'  and value < 70  and value != -127 and $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max/Min moisture of the day",
   "type": "graph",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MIN(\"value\") FROM \"mqtt_consumer\"  WHERE topic = 'esp/moisture'   and value < 70 and value != -127 and $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MAX(\"value\") FROM \"mqtt_consumer\"  WHERE  topic = 'esp/moisture'   and value < 70  and value != -127 and $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max/Min PH of the day",
   "type": "graph",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MIN(\"value\") FROM \"mqtt_consumer\"  WHERE  ( topic = 'esp/ph'  ) and  $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MAX(\"value\") FROM \"mqtt_consumer\"  WHERE  ( topic = 'esp/ph'  ) and  $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}